web:
  upload-path: D:\static\image
  endpoint: http://localhost:8080/lostandfound

logging:
  file:
    path: D:/static
  level:
    root: info

spring:
  mvc:
    static-path-pattern: /**  # 静态文件的匹配
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,\
      classpath:/static/,classpath:/public/,file:${web.upload-path}  # 静态文件的查找路径