server:
  servlet:
    context-path: /lostandfound
  port: 8080

spring:
  profiles:
    active: prod #默认为开发环境
  servlet:
    multipart:
      max-file-size: 10MB  # 文件大小限制为10MB
  resources:
    cache:
      cachecontrol:
        max-age: 2592000
        must-revalidate: on
        no-cache: on
jwt:
  tokenHeader: Authorization
  secret: lostandfound-secret
  expiration: 604800
  tokenHead: Bearer



list:
  timeOfDay:
    - 早间
    - 第一节课
    - 第二节课
    - 第三节课
    - 第四节课
    - 午间
    - 第五节课
    - 第六节课
    - 第七节课
    - 第八节课
    - 晚间
    - 第九节课
    - 第十节课

source:
  ignored:
    urls:
      - /wxUser/login
      - /admin/login
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.jpg
      - /**/*.ico
      - /**/*.mp4
      - /actuator/**
      - /searchTest

mybatis:
  mapper-locations:
    - classpath*:/team/cfc/lostandfound/mapper/*.xml

#logging:
#  level:
#    team:
#      cfc:
#        lostandfound:
#          dao:
#            debug


spring.mail.host: smtp.qq.com
spring.mail.username: xxxxxx
spring.mail.password: xxxxxx
spring.mail.default-encoding: UTF-8
spring.mail.port: 465
spring.mail.properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.debug: true
redis:
  key:
    prefix:
      inviteCode: "region:invite:code"
    expire:
      inviteCode: 86400 # (24小时)验证码超期时间(秒)

